version: '3.1'

services:
  pg:
    image: "postgres:12-alpine"
    restart: always
    ports: 
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
